
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.balsarystisa.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.balsarystisa.item.WhitePhosphorusOreItem;
import net.mcreator.balsarystisa.item.Tugstium_1SwordItem;
import net.mcreator.balsarystisa.item.Tugstium_1ShovelItem;
import net.mcreator.balsarystisa.item.Tugstium_1PickaxeItem;
import net.mcreator.balsarystisa.item.Tugstium_1HoeItem;
import net.mcreator.balsarystisa.item.Tugstium_1AxeItem;
import net.mcreator.balsarystisa.item.TugstiumItem;
import net.mcreator.balsarystisa.item.TugstiumArmorArmorItem;
import net.mcreator.balsarystisa.item.SubDermalArmorTier3Item;
import net.mcreator.balsarystisa.item.SubDermalArmorTier2Item;
import net.mcreator.balsarystisa.item.SubDermalArmorTier1Item;
import net.mcreator.balsarystisa.item.SapBottleItem;
import net.mcreator.balsarystisa.item.RespirationMedaillonItem;
import net.mcreator.balsarystisa.item.RedPhosphorusOreItem;
import net.mcreator.balsarystisa.item.NightVisionMedaillonItem;
import net.mcreator.balsarystisa.item.NanoTechnologiePlateItem;
import net.mcreator.balsarystisa.item.NanoTechnologieIngotItem;
import net.mcreator.balsarystisa.item.NanoTechnologieArmorItem;
import net.mcreator.balsarystisa.item.NanoSwordItem;
import net.mcreator.balsarystisa.item.NanoShovelItem;
import net.mcreator.balsarystisa.item.NanoPlateItem;
import net.mcreator.balsarystisa.item.NanoPickaxeItem;
import net.mcreator.balsarystisa.item.NanoIngotItem;
import net.mcreator.balsarystisa.item.NanoHoeItem;
import net.mcreator.balsarystisa.item.NanoCraftingHammerItem;
import net.mcreator.balsarystisa.item.NanoAxeItem;
import net.mcreator.balsarystisa.item.NanoArmorItem;
import net.mcreator.balsarystisa.item.MatchboxItem;
import net.mcreator.balsarystisa.item.Matchbox1Item;
import net.mcreator.balsarystisa.item.MatchLieItem;
import net.mcreator.balsarystisa.item.MatchItem;
import net.mcreator.balsarystisa.item.InvisibleCamotiers3Item;
import net.mcreator.balsarystisa.item.InvisibleCamotiers2Item;
import net.mcreator.balsarystisa.item.InvisibleCamoCyberwareItem;
import net.mcreator.balsarystisa.item.InvisibleCamo3Item;
import net.mcreator.balsarystisa.item.InvisibleCamo2Item;
import net.mcreator.balsarystisa.item.InvisibleCamo1Item;
import net.mcreator.balsarystisa.item.IgnisiumIngotItem;
import net.mcreator.balsarystisa.item.HungerMedaillonItem;
import net.mcreator.balsarystisa.item.HealthBoostMedaillonItem;
import net.mcreator.balsarystisa.item.FireworksItem;
import net.mcreator.balsarystisa.item.FallDamageMedaillonItem;
import net.mcreator.balsarystisa.item.EnderPearlImplantItem;
import net.mcreator.balsarystisa.item.EnderEyeCyberwareTier3Item;
import net.mcreator.balsarystisa.item.EnderEyeCyberwareTier2Item;
import net.mcreator.balsarystisa.item.EnderEyeCyberwareTier1Item;
import net.mcreator.balsarystisa.item.DiamondFlintItem;
import net.mcreator.balsarystisa.item.CompactTugstiumIngotItem;
import net.mcreator.balsarystisa.item.CompactNetheriteIngotItem;
import net.mcreator.balsarystisa.item.CompactNanoTechnologieIngotItem;
import net.mcreator.balsarystisa.item.CompactNanoIngotItem;
import net.mcreator.balsarystisa.item.CompactIronIngotItem;
import net.mcreator.balsarystisa.item.CompactIgnisiumIngotItem;
import net.mcreator.balsarystisa.item.CompactGoldIngotItem;
import net.mcreator.balsarystisa.item.CompactCopperIngotItem;
import net.mcreator.balsarystisa.item.CobaltSwordItem;
import net.mcreator.balsarystisa.item.CobaltShovelItem;
import net.mcreator.balsarystisa.item.CobaltPickaxeItem;
import net.mcreator.balsarystisa.item.CobaltIngotItem;
import net.mcreator.balsarystisa.item.CobaltHoeItem;
import net.mcreator.balsarystisa.item.CobaltAxeItem;
import net.mcreator.balsarystisa.item.CobaltArmorItem;
import net.mcreator.balsarystisa.item.BlackPhosphorusOreItem;
import net.mcreator.balsarystisa.item.BasondubataillondexplorationItem;
import net.mcreator.balsarystisa.item.BaguetteSwordItem;
import net.mcreator.balsarystisa.item.BaguetteShovelItem;
import net.mcreator.balsarystisa.item.BaguettePickaxeItem;
import net.mcreator.balsarystisa.item.BaguetteItem;
import net.mcreator.balsarystisa.item.BaguetteHoeItem;
import net.mcreator.balsarystisa.item.BaguetteAxeItem;
import net.mcreator.balsarystisa.item.ArystisaWorldItem;
import net.mcreator.balsarystisa.item.AmberItem;
import net.mcreator.balsarystisa.BalsArystisaMod;

public class BalsArystisaModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, BalsArystisaMod.MODID);
	public static final RegistryObject<Item> RUNNED_STONE_BRICKS = block(BalsArystisaModBlocks.RUNNED_STONE_BRICKS);
	public static final RegistryObject<Item> ARYSTIS_SPAWNER = block(BalsArystisaModBlocks.ARYSTIS_SPAWNER);
	public static final RegistryObject<Item> ARYSTIS_SPAWNER_NO_ACTIVETED = block(BalsArystisaModBlocks.ARYSTIS_SPAWNER_NO_ACTIVETED);
	public static final RegistryObject<Item> BLOCTUGSTIUM = block(BalsArystisaModBlocks.BLOCTUGSTIUM);
	public static final RegistryObject<Item> NANO_BLOCK = block(BalsArystisaModBlocks.NANO_BLOCK);
	public static final RegistryObject<Item> IGNISIUM_ORE = block(BalsArystisaModBlocks.IGNISIUM_ORE);
	public static final RegistryObject<Item> COBALTORE = block(BalsArystisaModBlocks.COBALTORE);
	public static final RegistryObject<Item> TUGSTIUMORE = block(BalsArystisaModBlocks.TUGSTIUMORE);
	public static final RegistryObject<Item> NANO_ORE = block(BalsArystisaModBlocks.NANO_ORE);
	public static final RegistryObject<Item> BLACK_PHOSPHORUS_BLOCK = block(BalsArystisaModBlocks.BLACK_PHOSPHORUS_BLOCK);
	public static final RegistryObject<Item> NANO_TECHNOLOGIE_BLOCK = block(BalsArystisaModBlocks.NANO_TECHNOLOGIE_BLOCK);
	public static final RegistryObject<Item> RED_PHOSPHORUS_BLOCK = block(BalsArystisaModBlocks.RED_PHOSPHORUS_BLOCK);
	public static final RegistryObject<Item> FORMER_GRAVEL = block(BalsArystisaModBlocks.FORMER_GRAVEL);
	public static final RegistryObject<Item> ARYSTING_LEAVES = block(BalsArystisaModBlocks.ARYSTING_LEAVES);
	public static final RegistryObject<Item> ENCHANT_LEAVES = block(BalsArystisaModBlocks.ENCHANT_LEAVES);
	public static final RegistryObject<Item> ARYSTING_WOOD = block(BalsArystisaModBlocks.ARYSTING_WOOD);
	public static final RegistryObject<Item> ARYSTING_LOG = block(BalsArystisaModBlocks.ARYSTING_LOG);
	public static final RegistryObject<Item> AMBER_ORE_ARYSTING_LOG = block(BalsArystisaModBlocks.AMBER_ORE_ARYSTING_LOG);
	public static final RegistryObject<Item> ARYSTING_PLANKS = block(BalsArystisaModBlocks.ARYSTING_PLANKS);
	public static final RegistryObject<Item> ARYSTING_STAIRS = block(BalsArystisaModBlocks.ARYSTING_STAIRS);
	public static final RegistryObject<Item> ARYSTING_SLAB = block(BalsArystisaModBlocks.ARYSTING_SLAB);
	public static final RegistryObject<Item> ARYSTING_FENCE = block(BalsArystisaModBlocks.ARYSTING_FENCE);
	public static final RegistryObject<Item> ARYSTING_FENCE_GATE = block(BalsArystisaModBlocks.ARYSTING_FENCE_GATE);
	public static final RegistryObject<Item> ARYSTING_PRESSURE_PLATE = block(BalsArystisaModBlocks.ARYSTING_PRESSURE_PLATE);
	public static final RegistryObject<Item> ARYSTING_BUTTON = block(BalsArystisaModBlocks.ARYSTING_BUTTON);
	public static final RegistryObject<Item> ENCHANT_WOOD = block(BalsArystisaModBlocks.ENCHANT_WOOD);
	public static final RegistryObject<Item> ENCHANT_LOG = block(BalsArystisaModBlocks.ENCHANT_LOG);
	public static final RegistryObject<Item> ENCHANT_PLANKS = block(BalsArystisaModBlocks.ENCHANT_PLANKS);
	public static final RegistryObject<Item> ENCHANT_STAIRS = block(BalsArystisaModBlocks.ENCHANT_STAIRS);
	public static final RegistryObject<Item> ENCHANT_SLAB = block(BalsArystisaModBlocks.ENCHANT_SLAB);
	public static final RegistryObject<Item> ENCHANT_FENCE = block(BalsArystisaModBlocks.ENCHANT_FENCE);
	public static final RegistryObject<Item> ENCHANT_FENCE_GATE = block(BalsArystisaModBlocks.ENCHANT_FENCE_GATE);
	public static final RegistryObject<Item> ENCHANT_PRESSURE_PLATE = block(BalsArystisaModBlocks.ENCHANT_PRESSURE_PLATE);
	public static final RegistryObject<Item> ENCHANT_BUTTON = block(BalsArystisaModBlocks.ENCHANT_BUTTON);
	public static final RegistryObject<Item> IGNISIUM_INGOT = REGISTRY.register("ignisium_ingot", () -> new IgnisiumIngotItem());
	public static final RegistryObject<Item> TUGSTIUM = REGISTRY.register("tugstium", () -> new TugstiumItem());
	public static final RegistryObject<Item> NANO_INGOT = REGISTRY.register("nano_ingot", () -> new NanoIngotItem());
	public static final RegistryObject<Item> NANO_PLATE = REGISTRY.register("nano_plate", () -> new NanoPlateItem());
	public static final RegistryObject<Item> NANO_TECHNOLOGIE_INGOT = REGISTRY.register("nano_technologie_ingot", () -> new NanoTechnologieIngotItem());
	public static final RegistryObject<Item> COMPACT_COPPER_INGOT = REGISTRY.register("compact_copper_ingot", () -> new CompactCopperIngotItem());
	public static final RegistryObject<Item> COMPACT_NANO_INGOT = REGISTRY.register("compact_nano_ingot", () -> new CompactNanoIngotItem());
	public static final RegistryObject<Item> COMPACT_IGNISIUM_INGOT = REGISTRY.register("compact_ignisium_ingot", () -> new CompactIgnisiumIngotItem());
	public static final RegistryObject<Item> COMPACT_IRON_INGOT = REGISTRY.register("compact_iron_ingot", () -> new CompactIronIngotItem());
	public static final RegistryObject<Item> TUGSTIUM_ARMOR_ARMOR_HELMET = REGISTRY.register("tugstium_armor_armor_helmet", () -> new TugstiumArmorArmorItem.Helmet());
	public static final RegistryObject<Item> TUGSTIUM_ARMOR_ARMOR_CHESTPLATE = REGISTRY.register("tugstium_armor_armor_chestplate", () -> new TugstiumArmorArmorItem.Chestplate());
	public static final RegistryObject<Item> TUGSTIUM_ARMOR_ARMOR_LEGGINGS = REGISTRY.register("tugstium_armor_armor_leggings", () -> new TugstiumArmorArmorItem.Leggings());
	public static final RegistryObject<Item> TUGSTIUM_ARMOR_ARMOR_BOOTS = REGISTRY.register("tugstium_armor_armor_boots", () -> new TugstiumArmorArmorItem.Boots());
	public static final RegistryObject<Item> COMPACT_TUGSTIUM_INGOT = REGISTRY.register("compact_tugstium_ingot", () -> new CompactTugstiumIngotItem());
	public static final RegistryObject<Item> COMPACT_GOLD_INGOT = REGISTRY.register("compact_gold_ingot", () -> new CompactGoldIngotItem());
	public static final RegistryObject<Item> NANO_ARMOR_HELMET = REGISTRY.register("nano_armor_helmet", () -> new NanoArmorItem.Helmet());
	public static final RegistryObject<Item> NANO_ARMOR_CHESTPLATE = REGISTRY.register("nano_armor_chestplate", () -> new NanoArmorItem.Chestplate());
	public static final RegistryObject<Item> NANO_ARMOR_LEGGINGS = REGISTRY.register("nano_armor_leggings", () -> new NanoArmorItem.Leggings());
	public static final RegistryObject<Item> NANO_ARMOR_BOOTS = REGISTRY.register("nano_armor_boots", () -> new NanoArmorItem.Boots());
	public static final RegistryObject<Item> COMPACT_NETHERITE_INGOT = REGISTRY.register("compact_netherite_ingot", () -> new CompactNetheriteIngotItem());
	public static final RegistryObject<Item> BAGUETTE = REGISTRY.register("baguette", () -> new BaguetteItem());
	public static final RegistryObject<Item> COMPACT_NANO_TECHNOLOGIE_INGOT = REGISTRY.register("compact_nano_technologie_ingot", () -> new CompactNanoTechnologieIngotItem());
	public static final RegistryObject<Item> BAGUETTE_SWORD = REGISTRY.register("baguette_sword", () -> new BaguetteSwordItem());
	public static final RegistryObject<Item> TUGSTIUM_1_SWORD = REGISTRY.register("tugstium_1_sword", () -> new Tugstium_1SwordItem());
	public static final RegistryObject<Item> NANO_TECHNOLOGIE_PLATE = REGISTRY.register("nano_technologie_plate", () -> new NanoTechnologiePlateItem());
	public static final RegistryObject<Item> NANO_SWORD = REGISTRY.register("nano_sword", () -> new NanoSwordItem());
	public static final RegistryObject<Item> BAGUETTE_PICKAXE = REGISTRY.register("baguette_pickaxe", () -> new BaguettePickaxeItem());
	public static final RegistryObject<Item> TUGSTIUM_1_PICKAXE = REGISTRY.register("tugstium_1_pickaxe", () -> new Tugstium_1PickaxeItem());
	public static final RegistryObject<Item> NANO_PICKAXE = REGISTRY.register("nano_pickaxe", () -> new NanoPickaxeItem());
	public static final RegistryObject<Item> BAGUETTE_AXE = REGISTRY.register("baguette_axe", () -> new BaguetteAxeItem());
	public static final RegistryObject<Item> TUGSTIUM_1_AXE = REGISTRY.register("tugstium_1_axe", () -> new Tugstium_1AxeItem());
	public static final RegistryObject<Item> NANO_AXE = REGISTRY.register("nano_axe", () -> new NanoAxeItem());
	public static final RegistryObject<Item> BAGUETTE_SHOVEL = REGISTRY.register("baguette_shovel", () -> new BaguetteShovelItem());
	public static final RegistryObject<Item> TUGSTIUM_1_SHOVEL = REGISTRY.register("tugstium_1_shovel", () -> new Tugstium_1ShovelItem());
	public static final RegistryObject<Item> NANO_SHOVEL = REGISTRY.register("nano_shovel", () -> new NanoShovelItem());
	public static final RegistryObject<Item> BAGUETTE_HOE = REGISTRY.register("baguette_hoe", () -> new BaguetteHoeItem());
	public static final RegistryObject<Item> TUGSTIUM_1_HOE = REGISTRY.register("tugstium_1_hoe", () -> new Tugstium_1HoeItem());
	public static final RegistryObject<Item> NANO_HOE = REGISTRY.register("nano_hoe", () -> new NanoHoeItem());
	public static final RegistryObject<Item> INVISIBLE_CAMO_CYBERWARE = REGISTRY.register("invisible_camo_cyberware", () -> new InvisibleCamoCyberwareItem());
	public static final RegistryObject<Item> INVISIBLE_CAMOTIERS_2 = REGISTRY.register("invisible_camotiers_2", () -> new InvisibleCamotiers2Item());
	public static final RegistryObject<Item> INVISIBLE_CAMOTIERS_3 = REGISTRY.register("invisible_camotiers_3", () -> new InvisibleCamotiers3Item());
	public static final RegistryObject<Item> SUB_DERMAL_ARMOR_TIER_1 = REGISTRY.register("sub_dermal_armor_tier_1", () -> new SubDermalArmorTier1Item());
	public static final RegistryObject<Item> SUB_DERMAL_ARMOR_TIER_2 = REGISTRY.register("sub_dermal_armor_tier_2", () -> new SubDermalArmorTier2Item());
	public static final RegistryObject<Item> SUB_DERMAL_ARMOR_TIER_3 = REGISTRY.register("sub_dermal_armor_tier_3", () -> new SubDermalArmorTier3Item());
	public static final RegistryObject<Item> SAP_BOTTLE = REGISTRY.register("sap_bottle", () -> new SapBottleItem());
	public static final RegistryObject<Item> ENDER_EYE_CYBERWARE_TIER_1 = REGISTRY.register("ender_eye_cyberware_tier_1", () -> new EnderEyeCyberwareTier1Item());
	public static final RegistryObject<Item> AMBER = REGISTRY.register("amber", () -> new AmberItem());
	public static final RegistryObject<Item> ENDER_EYE_CYBERWARE_TIER_2 = REGISTRY.register("ender_eye_cyberware_tier_2", () -> new EnderEyeCyberwareTier2Item());
	public static final RegistryObject<Item> DIAMOND_FLINT = REGISTRY.register("diamond_flint", () -> new DiamondFlintItem());
	public static final RegistryObject<Item> ENDER_EYE_CYBERWARE_TIER_3 = REGISTRY.register("ender_eye_cyberware_tier_3", () -> new EnderEyeCyberwareTier3Item());
	public static final RegistryObject<Item> ARYSTISA_WORLD = REGISTRY.register("arystisa_world", () -> new ArystisaWorldItem());
	public static final RegistryObject<Item> NANO_CRAFTING_HAMMER = REGISTRY.register("nano_crafting_hammer", () -> new NanoCraftingHammerItem());
	public static final RegistryObject<Item> ARYSTING_COW_SPAWN_EGG = REGISTRY.register("arysting_cow_spawn_egg", () -> new ForgeSpawnEggItem(BalsArystisaModEntities.ARYSTING_COW, -16764109, -16737895, new Item.Properties()));
	public static final RegistryObject<Item> BLASONDUBATAILLONDEXPLORATION = REGISTRY.register("blasondubataillondexploration", () -> new BasondubataillondexplorationItem());
	public static final RegistryObject<Item> IGNISIUM_BLOCK = block(BalsArystisaModBlocks.IGNISIUM_BLOCK);
	public static final RegistryObject<Item> NANO_CRAFTING_TABLE = block(BalsArystisaModBlocks.NANO_CRAFTING_TABLE);
	public static final RegistryObject<Item> WORK_STATION = block(BalsArystisaModBlocks.WORK_STATION);
	public static final RegistryObject<Item> IGNISIUM_CRAFTING_TABLE = block(BalsArystisaModBlocks.IGNISIUM_CRAFTING_TABLE);
	public static final RegistryObject<Item> IGNISIUM_SMELTER = block(BalsArystisaModBlocks.IGNISIUM_SMELTER);
	public static final RegistryObject<Item> NANO_TECHNOLOGIE_ARMOR_HELMET = REGISTRY.register("nano_technologie_armor_helmet", () -> new NanoTechnologieArmorItem.Helmet());
	public static final RegistryObject<Item> NANO_TECHNOLOGIE_ARMOR_CHESTPLATE = REGISTRY.register("nano_technologie_armor_chestplate", () -> new NanoTechnologieArmorItem.Chestplate());
	public static final RegistryObject<Item> NANO_TECHNOLOGIE_ARMOR_LEGGINGS = REGISTRY.register("nano_technologie_armor_leggings", () -> new NanoTechnologieArmorItem.Leggings());
	public static final RegistryObject<Item> NANO_TECHNOLOGIE_ARMOR_BOOTS = REGISTRY.register("nano_technologie_armor_boots", () -> new NanoTechnologieArmorItem.Boots());
	public static final RegistryObject<Item> WHITE_PHOSPHORUS_BLOCK = block(BalsArystisaModBlocks.WHITE_PHOSPHORUS_BLOCK);
	public static final RegistryObject<Item> MATCHBOX = REGISTRY.register("matchbox", () -> new MatchboxItem());
	public static final RegistryObject<Item> MATCH = REGISTRY.register("match", () -> new MatchItem());
	public static final RegistryObject<Item> MATCHBOX_1 = REGISTRY.register("matchbox_1", () -> new Matchbox1Item());
	public static final RegistryObject<Item> FIREWORKS = REGISTRY.register("fireworks", () -> new FireworksItem());
	public static final RegistryObject<Item> FALL_DAMAGE_MEDAILLON = REGISTRY.register("fall_damage_medaillon", () -> new FallDamageMedaillonItem());
	public static final RegistryObject<Item> HEALTH_BOOST_MEDAILLON = REGISTRY.register("health_boost_medaillon", () -> new HealthBoostMedaillonItem());
	public static final RegistryObject<Item> HUNGER_MEDAILLON = REGISTRY.register("hunger_medaillon", () -> new HungerMedaillonItem());
	public static final RegistryObject<Item> NIGHT_VISION_MEDAILLON = REGISTRY.register("night_vision_medaillon", () -> new NightVisionMedaillonItem());
	public static final RegistryObject<Item> RESPIRATION_MEDAILLON = REGISTRY.register("respiration_medaillon", () -> new RespirationMedaillonItem());
	public static final RegistryObject<Item> COBALT_ARMOR_HELMET = REGISTRY.register("cobalt_armor_helmet", () -> new CobaltArmorItem.Helmet());
	public static final RegistryObject<Item> COBALT_ARMOR_CHESTPLATE = REGISTRY.register("cobalt_armor_chestplate", () -> new CobaltArmorItem.Chestplate());
	public static final RegistryObject<Item> COBALT_ARMOR_LEGGINGS = REGISTRY.register("cobalt_armor_leggings", () -> new CobaltArmorItem.Leggings());
	public static final RegistryObject<Item> COBALT_ARMOR_BOOTS = REGISTRY.register("cobalt_armor_boots", () -> new CobaltArmorItem.Boots());
	public static final RegistryObject<Item> MATCH_LIE = REGISTRY.register("match_lie", () -> new MatchLieItem());
	public static final RegistryObject<Item> COBALT_INGOT = REGISTRY.register("cobalt_ingot", () -> new CobaltIngotItem());
	public static final RegistryObject<Item> WHITE_PHOSPHORUS_ORE = REGISTRY.register("white_phosphorus_ore", () -> new WhitePhosphorusOreItem());
	public static final RegistryObject<Item> BLACK_PHOSPHORUS_ORE = REGISTRY.register("black_phosphorus_ore", () -> new BlackPhosphorusOreItem());
	public static final RegistryObject<Item> RED_PHOSPHORUS_ORE = REGISTRY.register("red_phosphorus_ore", () -> new RedPhosphorusOreItem());
	public static final RegistryObject<Item> INVISIBLE_CAMO_1 = REGISTRY.register("invisible_camo_1", () -> new InvisibleCamo1Item());
	public static final RegistryObject<Item> INVISIBLE_CAMO_2 = REGISTRY.register("invisible_camo_2", () -> new InvisibleCamo2Item());
	public static final RegistryObject<Item> INVISIBLE_CAMO_3 = REGISTRY.register("invisible_camo_3", () -> new InvisibleCamo3Item());
	public static final RegistryObject<Item> ENDER_PEARL_IMPLANT = REGISTRY.register("ender_pearl_implant", () -> new EnderPearlImplantItem());
	public static final RegistryObject<Item> COBALT_PICKAXE = REGISTRY.register("cobalt_pickaxe", () -> new CobaltPickaxeItem());
	public static final RegistryObject<Item> COBALT_AXE = REGISTRY.register("cobalt_axe", () -> new CobaltAxeItem());
	public static final RegistryObject<Item> COBALT_SWORD = REGISTRY.register("cobalt_sword", () -> new CobaltSwordItem());
	public static final RegistryObject<Item> COBALT_SHOVEL = REGISTRY.register("cobalt_shovel", () -> new CobaltShovelItem());
	public static final RegistryObject<Item> COBALT_HOE = REGISTRY.register("cobalt_hoe", () -> new CobaltHoeItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
